In [1]:
import pandas as pd

In [2]:
config = pd.read_csv('config.csv')

In [3]:
config

            gamename  threshold  Unnamed: 2
0             Amidar      130.0         NaN
1            Assault     1800.0         NaN
2            Asterix     1440.0         NaN
3          Asteroids     1570.0         NaN
4           Atlantis  1267410.0         NaN
5          BankHeist      225.0         NaN
6         BattleZone    16600.0         NaN
7          BeamRider    10000.0         NaN
8            Berzerk      100.0         NaN
9            Bowling       50.0         NaN
10            Boxing       49.8         NaN
11          Breakout        9.5         NaN
12         Centipede    15000.0         NaN
13    ChopperCommand     3710.0         NaN
14      CrazyClimber    26430.0         NaN
15       DemonAttack     1166.5         NaN
16        DoubleDunk        0.2         NaN
17            Enduro       95.0         NaN
18      FishingDerby       49.0         NaN
19           Freeway       31.0         NaN
20         Frostbite      370.0         NaN
21            Gopher      582.0         NaN
22          Gravitar      805.0         NaN
23         IceHockey        4.1         NaN
24          Kangaroo    11200.0         NaN
25             Krull     8647.2         NaN
26  MontezumaRevenge        0.0         NaN
27      NameThisGame     4503.0         NaN
28           Phoenix     4041.0         NaN
29           PitFall        0.0         NaN
30              Pong       21.0         NaN
31        PrivateEye      100.0         NaN
32             Qbert      147.5         NaN
33         RiverRaid     5009.0         NaN
34        RoadRunner    16590.0         NaN
35          Robotank       11.9         NaN
36          Seaquest     1390.0         NaN
37            Skiing    15442.5         NaN
38           Solaris     2090.0         NaN
39     SpaceInvaders      678.5         NaN
40        StarGunner     1470.0         NaN
41            Tennis        4.5         NaN
42         TimePilot     4970.0         NaN
43         Tutankham      130.3         NaN
44           UpNDown    67974.0         NaN
45           Venture      760.0         NaN
46      VideoPinball    22834.0         NaN
47       WizardOfWor     3480.0         NaN
48       YarsRevenge    16401.0         NaN
49            Zaxxon     6380.0         NaN